CREATE TABLE contacts(id INT AUTO_INCREMENT, name CHAR(30) NOT NULL, email CHAR(30));
CREATE TABLE contacts1(id INT AUTO_INCREMENT, name1 CHAR(30) NOT NULL, email1 CHAR(30));
INSERT INTO contacts(name, email) VALUES('Rem', 'Rem.collier@ucd.ie');
INSERT INTO contacts1(name1, email1) VALUES('Rem1', 'Rem1.collier@ucd.ie');
INSERT INTO contacts(name, email) VALUES('test', 'test.test@ucd.ie');
SELECT * FROM contacts WHERE id < 2;
SELECT * FROM contacts WHERE id <= 2;
SELECT * FROM contacts WHERE id > 0;
SELECT * FROM contacts WHERE id >= 0;
SELECT * FROM contacts WHERE id = 1;
SELECT * FROM contacts WHERE id <> 1;
SELECT * FROM contacts WHERE name LIKE '%R';
SELECT * FROM contacts WHERE name LIKE 'm%';
SELECT * FROM contacts WHERE name LIKE '%es%';
UPDATE contacts SET name = 'new test' WHERE id = 2;
SELECT * FROM contacts;
DELETE FROM contacts WHERE id=2;
SELECT * FROM contacts;
DROP TABLE contacts;
DROP TABLE mapsql.tables;
SELECT * FROM contacts;
SELECT * FROM contacts1;
CREATE TABLE contacts(id INT AUTO_INCREMENT, name CHAR(30) NOT NULL, email CHAR(30));
INSERT INTO contacts(email) VALUES('Rem.collier@ucd.ie');