/* Generated By:JJTree&JavaCC: Do not edit this line. MapSQLConstants.java */
package mapsql.shell.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MapSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TABLE = 7;
  /** RegularExpression Id. */
  int CREATE = 8;
  /** RegularExpression Id. */
  int DROP = 9;
  /** RegularExpression Id. */
  int SELECT = 10;
  /** RegularExpression Id. */
  int FROM = 11;
  /** RegularExpression Id. */
  int WHERE = 12;
  /** RegularExpression Id. */
  int INSERT = 13;
  /** RegularExpression Id. */
  int INTO = 14;
  /** RegularExpression Id. */
  int VALUES = 15;
  /** RegularExpression Id. */
  int UPDATE = 16;
  /** RegularExpression Id. */
  int SET = 17;
  /** RegularExpression Id. */
  int DELETE = 18;
  /** RegularExpression Id. */
  int QUIT = 19;
  /** RegularExpression Id. */
  int SOURCE = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int WILDCARD = 23;
  /** RegularExpression Id. */
  int INT = 24;
  /** RegularExpression Id. */
  int CHAR = 25;
  /** RegularExpression Id. */
  int FIELD_MODIFIERS = 26;
  /** RegularExpression Id. */
  int COMPARISON_OPERATOR = 27;
  /** RegularExpression Id. */
  int LESS_THAN = 28;
  /** RegularExpression Id. */
  int GREATER_THAN = 29;
  /** RegularExpression Id. */
  int ADD_OPERATOR = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;
  /** RegularExpression Id. */
  int NUMBER_LITERAL = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int ADVPUNCT = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"TABLE\"",
    "\"CREATE\"",
    "\"DROP\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"UPDATE\"",
    "\"SET\"",
    "\"DELETE\"",
    "\"QUIT\"",
    "\"SOURCE\"",
    "\"AND\"",
    "\"OR\"",
    "\"*\"",
    "<INT>",
    "<CHAR>",
    "<FIELD_MODIFIERS>",
    "<COMPARISON_OPERATOR>",
    "\"<\"",
    "\">\"",
    "<ADD_OPERATOR>",
    "<STRING>",
    "<IDENTIFIER>",
    "<NUMBER_LITERAL>",
    "<DIGIT>",
    "<LETTER>",
    "<ADVPUNCT>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
