/* Generated By:JavaCC: Do not edit this line. MapSQLTreeConstants.java Version 5.0 */
package mapsql.shell.parser;

public interface MapSQLTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCREATETABLE = 2;
  public int JJTSELECT = 3;
  public int JJTINSERT = 4;
  public int JJTUPDATE = 5;
  public int JJTDELETE = 6;
  public int JJTDROPTABLE = 7;
  public int JJTSOURCE = 8;
  public int JJTQUIT = 9;
  public int JJTASSIGNMENTS = 10;
  public int JJTASSIGNMENT = 11;
  public int JJTFIELD = 12;
  public int JJTCOLUMNS = 13;
  public int JJTVALUES = 14;
  public int JJTORCONDITION = 15;
  public int JJTANDCONDITION = 16;
  public int JJTCONDITION = 17;
  public int JJTWILDCARD = 18;
  public int JJTMODIFIER = 19;
  public int JJTIDENTIFIER = 20;
  public int JJTCHAR = 21;
  public int JJTINT = 22;
  public int JJTSTRING = 23;
  public int JJTNUMBER = 24;
  public int JJTUNSIGNEDNUMBER = 25;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "CreateTable",
    "Select",
    "Insert",
    "Update",
    "Delete",
    "DropTable",
    "Source",
    "Quit",
    "Assignments",
    "Assignment",
    "Field",
    "Columns",
    "Values",
    "OrCondition",
    "AndCondition",
    "Condition",
    "Wildcard",
    "Modifier",
    "Identifier",
    "Char",
    "Int",
    "String",
    "Number",
    "UnsignedNumber",
  };
}
/* JavaCC - OriginalChecksum=0054b44be3282adee994347e9f5ed61a (do not edit this line) */
