# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944718653a7cd7ee48d9dbd3b6bdab09bc552e34400a8f38fb18577a39d52e19783d41bfdc937109baad285ec32cf0dcd803b5687f5230f8480022fa37522619

test:
  secret_key_base: d858bde6432e7c296ba5c7647c2b1c06c75772ee21f6dafcd4120aba3af7246f08b69e437063888c7a5b5d2c05c1d938dc0fcf26bb9674fd746c8701b93cca41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
